console.log("hello")

console.log(document.body)
document.body.firstChild
document.body.lastChild
document.body.childNodes
document.body.children
document.body.parentNode
document.body.parentElement
document.body.nextSibling
document.body.previousSibling
document.body.nextElementSibling
document.body.previousElementSibling
document.body.firstElementChild
document.body.lastElementChild
document.body.hasChildElement
document.body.hasChildNodes
document.body.hasAttributes
document.body.getAttribute
document.body.setAttribute
document.body.removeAttribute
document.body.style
document.body.getAttribute("style")
document.body.setAttribute("style", "color: red")
document.body.removeAttribute("style")
document.body.className
document.body.classList
document.body.classList.add
document.body.classList.remove
document.body.classList.toggle
document.body.classList.contains
document.body.classList.item
document.body.classList.length
document.body.classList[0]
document.body.classList[1]